// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnMZ4FOApzzCWI0UDaptr_SLNKLDC2Grg',
    appId: '1:579829938341:web:9abee742372cb057f0754c',
    messagingSenderId: '579829938341',
    projectId: 'flutter-fitness-tracker-b574c',
    authDomain: 'flutter-fitness-tracker-b574c.firebaseapp.com',
    storageBucket: 'flutter-fitness-tracker-b574c.firebasestorage.app',
    measurementId: 'G-4ZV8BMETWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoqrsDoOYgIB-aeAbMq9eOVcu0C16_6oI',
    appId: '1:579829938341:android:8de764e85d33a80bf0754c',
    messagingSenderId: '579829938341',
    projectId: 'flutter-fitness-tracker-b574c',
    storageBucket: 'flutter-fitness-tracker-b574c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzePDtvLdwVv5TOtWsxmlvLMYmC6j3hI',
    appId: '1:579829938341:ios:1c8e38ab997a5e16f0754c',
    messagingSenderId: '579829938341',
    projectId: 'flutter-fitness-tracker-b574c',
    storageBucket: 'flutter-fitness-tracker-b574c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitnessTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzePDtvLdwVv5TOtWsxmlvLMYmC6j3hI',
    appId: '1:579829938341:ios:1c8e38ab997a5e16f0754c',
    messagingSenderId: '579829938341',
    projectId: 'flutter-fitness-tracker-b574c',
    storageBucket: 'flutter-fitness-tracker-b574c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFitnessTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnMZ4FOApzzCWI0UDaptr_SLNKLDC2Grg',
    appId: '1:579829938341:web:10803e3e74c94c2bf0754c',
    messagingSenderId: '579829938341',
    projectId: 'flutter-fitness-tracker-b574c',
    authDomain: 'flutter-fitness-tracker-b574c.firebaseapp.com',
    storageBucket: 'flutter-fitness-tracker-b574c.firebasestorage.app',
    measurementId: 'G-GMDMFGNKCB',
  );

}