import '../models/exercise_plan_model.dart';

class ExercisePlanService {
  static List<ExercisePlan> getPredefinedPlans() {
    return [
      _beginnerPlan(),
      _intermediatePlan(),
      _advancedPlan(),
    ];
  }

  static List<ExercisePlan> getPlansByLevel(String level) {
    return getPredefinedPlans().where((plan) => plan.level == level).toList();
  }

  static ExercisePlan? getPlanById(String id) {
    try {
      return getPredefinedPlans().firstWhere((plan) => plan.id == id);
    } catch (e) {
      return null;
    }
  }

  static ExercisePlan _beginnerPlan() {
    return ExercisePlan(
      id: 'beginner_full_body',
      name: 'Beginner Full Body',
      description: 'A comprehensive 4-week program designed for fitness beginners. Focus on building basic strength, improving cardiovascular health, and establishing healthy exercise habits.',
      level: 'beginner',
      category: 'full_body',
      durationWeeks: 4,
      workoutsPerWeek: 3,
      estimatedCaloriesPerSession: 250,
      imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=400&h=300&fit=crop',
      ],
      videoUrls: [
        'https://www.youtube.com/watch?v=ixkQaZXVQjs', // Beginner workout video
        'https://www.youtube.com/watch?v=UBMk30rjy0o', // Basic exercises
      ],
      thumbnailUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=300&h=200&fit=crop',
      benefits: [
        'Build basic strength and endurance',
        'Improve cardiovascular health',
        'Learn proper exercise form',
        'Establish workout routine',
        'Boost energy levels'
      ],
      equipment: [
        'Body weight only',
        'Optional: Light dumbbells',
        'Exercise mat'
      ],
      exercises: [
        ExerciseDay(
          dayNumber: 1,
          title: 'Upper Body Foundation',
          estimatedDurationMinutes: 25,
          exercises: [
            Exercise(
              name: 'Push-ups (Modified)',
              description: 'Start with knee push-ups to build upper body strength',
              type: 'strength',
              sets: 2,
              reps: 8,
              restSeconds: 60,
              difficulty: 'easy',
              instructions: 'Keep your body straight, lower chest to ground, push back up',
              imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
              videoUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
              gifUrl: 'https://media.giphy.com/media/3o7TKF1fSIs1R19B8k/giphy.gif',
            ),
            Exercise(
              name: 'Wall Sits',
              description: 'Build leg strength and endurance',
              type: 'strength',
              durationSeconds: 20,
              restSeconds: 45,
              difficulty: 'easy',
              instructions: 'Back against wall, slide down until thighs parallel to floor',
            ),
            Exercise(
              name: 'Plank',
              description: 'Core strengthening exercise',
              type: 'strength',
              durationSeconds: 15,
              restSeconds: 45,
              difficulty: 'easy',
              instructions: 'Hold straight line from head to heels',
            ),
            Exercise(
              name: 'Marching in Place',
              description: 'Light cardio to finish',
              type: 'cardio',
              durationSeconds: 120,
              difficulty: 'easy',
              instructions: 'Lift knees high, pump arms',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 2,
          title: 'Lower Body & Core',
          estimatedDurationMinutes: 25,
          exercises: [
            Exercise(
              name: 'Bodyweight Squats',
              description: 'Basic leg strengthening exercise',
              type: 'strength',
              sets: 2,
              reps: 10,
              restSeconds: 60,
              difficulty: 'easy',
              instructions: 'Feet shoulder-width apart, lower as if sitting in chair',
              imageUrl: 'https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?w=400&h=300&fit=crop',
              videoUrl: 'https://www.youtube.com/watch?v=aclHkVaku9U',
              gifUrl: 'https://media.giphy.com/media/l0HlvtIPzPdt2usKs/giphy.gif',
            ),
            Exercise(
              name: 'Glute Bridges',
              description: 'Strengthen glutes and hamstrings',
              type: 'strength',
              sets: 2,
              reps: 12,
              restSeconds: 45,
              difficulty: 'easy',
              instructions: 'Lie on back, lift hips up, squeeze glutes',
            ),
            Exercise(
              name: 'Modified Crunches',
              description: 'Core strengthening',
              type: 'strength',
              sets: 2,
              reps: 10,
              restSeconds: 45,
              difficulty: 'easy',
              instructions: 'Hands behind head, lift shoulders off ground',
            ),
            Exercise(
              name: 'Step-ups (Using stairs)',
              description: 'Functional leg exercise',
              type: 'cardio',
              sets: 2,
              reps: 8,
              restSeconds: 60,
              difficulty: 'easy',
              instructions: 'Step up onto stair, step down with control',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 3,
          title: 'Full Body Circuit',
          estimatedDurationMinutes: 30,
          exercises: [
            Exercise(
              name: 'Jumping Jacks',
              description: 'Full body warm-up',
              type: 'cardio',
              durationSeconds: 30,
              restSeconds: 30,
              difficulty: 'easy',
              instructions: 'Jump feet apart while raising arms overhead',
            ),
            Exercise(
              name: 'Lunges',
              description: 'Single leg strengthening',
              type: 'strength',
              sets: 2,
              reps: 6,
              restSeconds: 60,
              difficulty: 'easy',
              instructions: 'Step forward, lower back knee toward ground',
            ),
            Exercise(
              name: 'Arm Circles',
              description: 'Shoulder mobility and strength',
              type: 'strength',
              durationSeconds: 30,
              restSeconds: 30,
              difficulty: 'easy',
              instructions: 'Extend arms, make small then large circles',
            ),
            Exercise(
              name: 'Dead Bug',
              description: 'Core stability exercise',
              type: 'strength',
              sets: 2,
              reps: 8,
              restSeconds: 45,
              difficulty: 'easy',
              instructions: 'Lie on back, extend opposite arm and leg',
            ),
          ],
        ),
      ],
    );
  }

  static ExercisePlan _intermediatePlan() {
    return ExercisePlan(
      id: 'intermediate_strength',
      name: 'Intermediate Strength Builder',
      description: 'A 6-week progressive strength training program for those with basic fitness experience. Builds muscle, increases strength, and improves overall fitness.',
      level: 'intermediate',
      category: 'strength',
      durationWeeks: 6,
      workoutsPerWeek: 4,
      estimatedCaloriesPerSession: 350,
      imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=800&h=600&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=400&h=300&fit=crop',
      ],
      videoUrls: [
        'https://www.youtube.com/watch?v=R6gZoAzAhCg', // Intermediate strength training
        'https://www.youtube.com/watch?v=IODxDxX7oi4', // Dumbbell workout
      ],
      thumbnailUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=300&h=200&fit=crop',
      benefits: [
        'Increase muscle mass and strength',
        'Improve bone density',
        'Boost metabolism',
        'Enhance functional movement',
        'Better body composition'
      ],
      equipment: [
        'Dumbbells (various weights)',
        'Resistance bands',
        'Exercise mat',
        'Pull-up bar (optional)'
      ],
      exercises: [
        ExerciseDay(
          dayNumber: 1,
          title: 'Upper Body Power',
          estimatedDurationMinutes: 40,
          exercises: [
            Exercise(
              name: 'Push-ups',
              description: 'Standard push-ups for upper body strength',
              type: 'strength',
              sets: 3,
              reps: 12,
              restSeconds: 60,
              difficulty: 'moderate',
              instructions: 'Full range of motion, control the movement',
            ),
            Exercise(
              name: 'Dumbbell Rows',
              description: 'Back strengthening exercise',
              type: 'strength',
              sets: 3,
              reps: 10,
              restSeconds: 75,
              difficulty: 'moderate',
              instructions: 'Bend over, pull weight to hip, squeeze shoulder blades',
            ),
            Exercise(
              name: 'Overhead Press',
              description: 'Shoulder and arm strengthening',
              type: 'strength',
              sets: 3,
              reps: 8,
              restSeconds: 90,
              difficulty: 'moderate',
              instructions: 'Press weight overhead, keep core tight',
            ),
            Exercise(
              name: 'Tricep Dips',
              description: 'Tricep strengthening using chair',
              type: 'strength',
              sets: 3,
              reps: 10,
              restSeconds: 60,
              difficulty: 'moderate',
              instructions: 'Lower body using arms, push back up',
            ),
            Exercise(
              name: 'Plank to Push-up',
              description: 'Dynamic core and upper body',
              type: 'strength',
              sets: 2,
              reps: 8,
              restSeconds: 60,
              difficulty: 'moderate',
              instructions: 'Start in plank, move to push-up position and back',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 2,
          title: 'Lower Body Strength',
          estimatedDurationMinutes: 40,
          exercises: [
            Exercise(
              name: 'Goblet Squats',
              description: 'Squats holding weight at chest',
              type: 'strength',
              sets: 3,
              reps: 12,
              restSeconds: 75,
              difficulty: 'moderate',
              instructions: 'Hold weight at chest, squat down keeping chest up',
            ),
            Exercise(
              name: 'Romanian Deadlifts',
              description: 'Hip hinge movement with weights',
              type: 'strength',
              sets: 3,
              reps: 10,
              restSeconds: 90,
              difficulty: 'moderate',
              instructions: 'Hinge at hips, lower weight while keeping back straight',
            ),
            Exercise(
              name: 'Walking Lunges',
              description: 'Dynamic single leg exercise',
              type: 'strength',
              sets: 3,
              reps: 12,
              restSeconds: 60,
              difficulty: 'moderate',
              instructions: 'Step forward into lunge, bring back leg forward',
            ),
            Exercise(
              name: 'Single Leg Glute Bridges',
              description: 'Unilateral glute strengthening',
              type: 'strength',
              sets: 2,
              reps: 10,
              restSeconds: 45,
              difficulty: 'moderate',
              instructions: 'One foot on ground, lift hips with one leg',
            ),
            Exercise(
              name: 'Calf Raises',
              description: 'Lower leg strengthening',
              type: 'strength',
              sets: 3,
              reps: 15,
              restSeconds: 45,
              difficulty: 'moderate',
              instructions: 'Rise up on toes, lower with control',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 3,
          title: 'Core & Cardio',
          estimatedDurationMinutes: 35,
          exercises: [
            Exercise(
              name: 'Mountain Climbers',
              description: 'High intensity cardio and core',
              type: 'cardio',
              durationSeconds: 45,
              restSeconds: 15,
              difficulty: 'moderate',
              instructions: 'Plank position, alternate bringing knees to chest',
            ),
            Exercise(
              name: 'Russian Twists',
              description: 'Rotational core exercise',
              type: 'strength',
              sets: 3,
              reps: 20,
              restSeconds: 45,
              difficulty: 'moderate',
              instructions: 'Sit with feet up, rotate torso side to side',
            ),
            Exercise(
              name: 'Burpees',
              description: 'Full body explosive movement',
              type: 'cardio',
              sets: 3,
              reps: 8,
              restSeconds: 90,
              difficulty: 'moderate',
              instructions: 'Squat, jump back to plank, push-up, jump forward, jump up',
            ),
            Exercise(
              name: 'Bicycle Crunches',
              description: 'Dynamic core exercise',
              type: 'strength',
              sets: 3,
              reps: 16,
              restSeconds: 45,
              difficulty: 'moderate',
              instructions: 'Alternate bringing elbow to opposite knee',
            ),
            Exercise(
              name: 'High Knees',
              description: 'Cardio finisher',
              type: 'cardio',
              durationSeconds: 60,
              difficulty: 'moderate',
              instructions: 'Run in place lifting knees high',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 4,
          title: 'Full Body Circuit',
          estimatedDurationMinutes: 45,
          exercises: [
            Exercise(
              name: 'Thrusters',
              description: 'Squat to overhead press combination',
              type: 'strength',
              sets: 3,
              reps: 10,
              restSeconds: 75,
              difficulty: 'moderate',
              instructions: 'Squat down, stand up and press weights overhead',
            ),
            Exercise(
              name: 'Renegade Rows',
              description: 'Plank with rowing movement',
              type: 'strength',
              sets: 3,
              reps: 8,
              restSeconds: 90,
              difficulty: 'moderate',
              instructions: 'Plank position with weights, row one arm at a time',
            ),
            Exercise(
              name: 'Jump Squats',
              description: 'Explosive lower body exercise',
              type: 'cardio',
              sets: 3,
              reps: 12,
              restSeconds: 60,
              difficulty: 'moderate',
              instructions: 'Squat down, jump up explosively',
            ),
            Exercise(
              name: 'Pike Push-ups',
              description: 'Shoulder-focused push-up variation',
              type: 'strength',
              sets: 2,
              reps: 8,
              restSeconds: 60,
              difficulty: 'moderate',
              instructions: 'Downward dog position, lower head toward ground',
            ),
          ],
        ),
      ],
    );
  }

  static ExercisePlan _advancedPlan() {
    return ExercisePlan(
      id: 'advanced_hiit',
      name: 'Advanced HIIT Challenge',
      description: 'An intense 8-week high-intensity interval training program for experienced athletes. Maximize fat burning, build explosive power, and push your limits.',
      level: 'advanced',
      category: 'hiit',
      durationWeeks: 8,
      workoutsPerWeek: 5,
      estimatedCaloriesPerSession: 450,
      imageUrl: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=800&h=600&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1517963628607-235ccdd5476c?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop',
      ],
      videoUrls: [
        'https://www.youtube.com/watch?v=ml6cT4AZdqI', // Advanced HIIT workout
        'https://www.youtube.com/watch?v=cZnsLVArIt8', // High intensity training
      ],
      thumbnailUrl: 'https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=300&h=200&fit=crop',
      benefits: [
        'Maximize fat burning and metabolism',
        'Build explosive power and speed',
        'Improve cardiovascular capacity',
        'Enhance athletic performance',
        'Time-efficient workouts'
      ],
      equipment: [
        'Dumbbells (heavy set)',
        'Kettlebells',
        'Pull-up bar',
        'Exercise mat',
        'Timer'
      ],
      exercises: [
        ExerciseDay(
          dayNumber: 1,
          title: 'Power & Strength',
          estimatedDurationMinutes: 50,
          exercises: [
            Exercise(
              name: 'Burpee Box Jumps',
              description: 'Explosive full body movement',
              type: 'cardio',
              sets: 4,
              reps: 8,
              restSeconds: 90,
              difficulty: 'hard',
              instructions: 'Burpee then jump onto elevated surface',
            ),
            Exercise(
              name: 'Weighted Pull-ups',
              description: 'Advanced upper body pulling',
              type: 'strength',
              sets: 4,
              reps: 6,
              restSeconds: 120,
              difficulty: 'hard',
              instructions: 'Add weight, pull chin over bar',
            ),
            Exercise(
              name: 'Pistol Squats',
              description: 'Single leg squat variation',
              type: 'strength',
              sets: 3,
              reps: 5,
              restSeconds: 90,
              difficulty: 'hard',
              instructions: 'Squat on one leg, other leg extended',
            ),
            Exercise(
              name: 'Handstand Push-ups',
              description: 'Inverted shoulder press',
              type: 'strength',
              sets: 3,
              reps: 5,
              restSeconds: 120,
              difficulty: 'hard',
              instructions: 'Against wall, lower head to ground and press up',
            ),
            Exercise(
              name: 'Turkish Get-ups',
              description: 'Complex full body movement',
              type: 'strength',
              sets: 2,
              reps: 5,
              restSeconds: 90,
              difficulty: 'hard',
              instructions: 'From lying to standing while holding weight overhead',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 2,
          title: 'Metabolic Conditioning',
          estimatedDurationMinutes: 45,
          exercises: [
            Exercise(
              name: 'Kettlebell Swings',
              description: 'Hip hinge power movement',
              type: 'cardio',
              durationSeconds: 45,
              restSeconds: 15,
              difficulty: 'hard',
              instructions: 'Hip hinge, swing kettlebell to shoulder height',
            ),
            Exercise(
              name: 'Battle Ropes',
              description: 'High intensity upper body cardio',
              type: 'cardio',
              durationSeconds: 30,
              restSeconds: 30,
              difficulty: 'hard',
              instructions: 'Alternate waves or simultaneous slams',
            ),
            Exercise(
              name: 'Box Jump Overs',
              description: 'Lateral explosive movement',
              type: 'cardio',
              durationSeconds: 40,
              restSeconds: 20,
              difficulty: 'hard',
              instructions: 'Jump over box, land and immediately jump back',
            ),
            Exercise(
              name: 'Thruster Clusters',
              description: 'Heavy squat to press',
              type: 'strength',
              sets: 5,
              reps: 3,
              restSeconds: 120,
              difficulty: 'hard',
              instructions: 'Heavy weight, squat to overhead press',
            ),
            Exercise(
              name: 'Sprint Intervals',
              description: 'Maximum effort running',
              type: 'cardio',
              durationSeconds: 20,
              restSeconds: 40,
              difficulty: 'hard',
              instructions: 'All-out sprint effort',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 3,
          title: 'Strength Endurance',
          estimatedDurationMinutes: 55,
          exercises: [
            Exercise(
              name: 'Weighted Dips',
              description: 'Advanced tricep and chest exercise',
              type: 'strength',
              sets: 4,
              reps: 8,
              restSeconds: 90,
              difficulty: 'hard',
              instructions: 'Add weight, lower body between parallel bars',
            ),
            Exercise(
              name: 'Single Arm Rows',
              description: 'Unilateral back strengthening',
              type: 'strength',
              sets: 4,
              reps: 8,
              restSeconds: 75,
              difficulty: 'hard',
              instructions: 'Heavy weight, one arm at a time',
            ),
            Exercise(
              name: 'Deficit Push-ups',
              description: 'Increased range of motion push-ups',
              type: 'strength',
              sets: 3,
              reps: 12,
              restSeconds: 60,
              difficulty: 'hard',
              instructions: 'Hands elevated, deeper push-up range',
            ),
            Exercise(
              name: 'L-Sits',
              description: 'Advanced core and arm strength',
              type: 'strength',
              durationSeconds: 20,
              restSeconds: 60,
              difficulty: 'hard',
              instructions: 'Sit with legs extended, lift body with arms',
            ),
            Exercise(
              name: 'Muscle-ups',
              description: 'Advanced pull-up to dip combination',
              type: 'strength',
              sets: 3,
              reps: 3,
              restSeconds: 120,
              difficulty: 'hard',
              instructions: 'Pull up and transition to dip position',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 4,
          title: 'Plyometric Power',
          estimatedDurationMinutes: 40,
          exercises: [
            Exercise(
              name: 'Depth Jumps',
              description: 'Drop and explosive jump',
              type: 'cardio',
              sets: 4,
              reps: 5,
              restSeconds: 120,
              difficulty: 'hard',
              instructions: 'Step off box, land and immediately jump up',
            ),
            Exercise(
              name: 'Clapping Push-ups',
              description: 'Explosive upper body power',
              type: 'strength',
              sets: 4,
              reps: 6,
              restSeconds: 90,
              difficulty: 'hard',
              instructions: 'Push up explosively, clap hands in air',
            ),
            Exercise(
              name: 'Broad Jumps',
              description: 'Horizontal jumping power',
              type: 'cardio',
              sets: 4,
              reps: 5,
              restSeconds: 90,
              difficulty: 'hard',
              instructions: 'Jump forward as far as possible',
            ),
            Exercise(
              name: 'Tuck Jumps',
              description: 'Vertical jumping with knee tuck',
              type: 'cardio',
              sets: 3,
              reps: 8,
              restSeconds: 75,
              difficulty: 'hard',
              instructions: 'Jump up, bring knees to chest',
            ),
            Exercise(
              name: 'Medicine Ball Slams',
              description: 'Explosive full body power',
              type: 'cardio',
              sets: 4,
              reps: 10,
              restSeconds: 60,
              difficulty: 'hard',
              instructions: 'Lift ball overhead, slam down with full force',
            ),
          ],
        ),
        ExerciseDay(
          dayNumber: 5,
          title: 'Ultimate Challenge',
          estimatedDurationMinutes: 60,
          exercises: [
            Exercise(
              name: 'Complex Circuit A',
              description: 'Deadlift to upright row to press',
              type: 'strength',
              sets: 3,
              reps: 6,
              restSeconds: 120,
              difficulty: 'hard',
              instructions: 'Flow from deadlift to row to overhead press',
            ),
            Exercise(
              name: 'Complex Circuit B',
              description: 'Squat to press to lunge',
              type: 'strength',
              sets: 3,
              reps: 6,
              restSeconds: 120,
              difficulty: 'hard',
              instructions: 'Squat, press overhead, step back to lunge',
            ),
            Exercise(
              name: 'Tabata Finisher',
              description: '4-minute high intensity protocol',
              type: 'cardio',
              durationSeconds: 240,
              difficulty: 'hard',
              instructions: '20 seconds all-out, 10 seconds rest, repeat 8 times',
            ),
          ],
        ),
      ],
    );
  }
}
